import { MapPin, Search } from "../site/Icons";
import type { Region } from "../../services/region.service";
import { CountryCombobox } from "../site/CountryCombobox";
import { LocationFilterCombobox } from "../site/LocationFilterCombobox";
type Sort = "az" | "za" | "nearest";
type Props = { query: string; country: string; province: string; city: string; sort: Sort; countries: Region[]; provinces: Region[]; cities: Region[]; provincesLoading: boolean; citiesLoading: boolean; locating: boolean; located: boolean; onLocate: () => void; onQueryChange: (value: string) => void; onCountryChange: (value: string) => void; onProvinceChange: (value: string) => void; onCityChange: (value: string) => void; onSortChange: (value: Sort) => void };
export function CompanyFilters(props: Props) {
  return <section className="company-filters"><div><label><Search /><input value={props.query} onChange={(event) => props.onQueryChange(event.target.value)} placeholder="Company name" /></label><CountryCombobox value={props.country} countries={props.countries} onChange={props.onCountryChange} /><LocationFilterCombobox value={props.province} disabled={props.country === "all"} loading={props.provincesLoading} placeholder="All provinces / states" loadingLabel="Loading provinces / states…" options={props.provinces.map((item) => ({ value: item.name, label: `${item.name}, ${props.country}` }))} onChange={props.onProvinceChange} /><LocationFilterCombobox value={props.city} disabled={props.country === "all" || props.province === "all"} loading={props.citiesLoading} placeholder="All cities" loadingLabel="Loading cities…" options={props.cities.map((item) => ({ value: item.name, label: `${item.name}, ${props.province}, ${props.country}` }))} onChange={props.onCityChange} /><button type="button" className={`company-locate${props.located ? " location-active" : ""}`} aria-pressed={props.located} disabled={props.locating} onClick={props.onLocate}><MapPin />{props.locating ? "Locating…" : props.located ? "Stop using my location" : "Use my location"}</button><select value={props.sort} onChange={(event) => props.onSortChange(event.target.value as Sort)}><option value="az">Name A–Z</option><option value="za">Name Z–A</option>{props.located && <option value="nearest">Nearest to me</option>}</select></div></section>;
}
