import { Close, Search, SlidersHorizontal } from "../site/Icons";

export type DateFilter = "any" | "7d" | "30d" | "range";
export type SortKey = "newest" | "oldest" | "nearest";

type BrowseFiltersProps = { query: string; category: string; location: string; dateFilter: DateFilter; from: string; to: string; sort: SortKey; categories: string[]; locations: string[]; showNearest: boolean; activeFilters: boolean; onQueryChange: (value: string) => void; onCategoryChange: (value: string) => void; onLocationChange: (value: string) => void; onDateFilterChange: (value: DateFilter) => void; onFromChange: (value: string) => void; onToChange: (value: string) => void; onSortChange: (value: SortKey) => void; onReset: () => void };

export function BrowseFilters({ query, category, location, dateFilter, from, to, sort, categories, locations, showNearest, activeFilters, onQueryChange, onCategoryChange, onLocationChange, onDateFilterChange, onFromChange, onToChange, onSortChange, onReset }: BrowseFiltersProps) {
  const dateOptions: [DateFilter, string][] = [["any", "Any time"], ["7d", "Last 7 days"], ["30d", "Last 30 days"], ["range", "Date range"]];
  return <section className="browse-filters"><div className="browse-filter-wrap"><div className="browse-filter-primary"><label className="browse-search"><Search /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Job title, company or skill" /></label><select value={category} onChange={(event) => onCategoryChange(event.target.value)}><option value="all">All categories</option>{categories.map((item) => <option key={item}>{item}</option>)}</select><select value={location} onChange={(event) => onLocationChange(event.target.value)}><option value="all">All locations</option>{locations.map((item) => <option key={item}>{item}</option>)}</select></div><div className="browse-filter-secondary"><span><SlidersHorizontal />Posted</span>{dateOptions.map(([value, label]) => <button key={value} type="button" className={dateFilter === value ? "active" : ""} onClick={() => onDateFilterChange(value)}>{label}</button>)}{dateFilter === "range" && <div className="browse-date-range"><input aria-label="From date" type="date" value={from} onChange={(event) => onFromChange(event.target.value)} /><span>to</span><input aria-label="To date" type="date" value={to} onChange={(event) => onToChange(event.target.value)} /></div>}<div className="browse-sort"><label htmlFor="browse-sort">Sort</label><select id="browse-sort" value={sort} onChange={(event) => onSortChange(event.target.value as SortKey)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option>{showNearest && <option value="nearest">Nearest to me</option>}</select></div>{activeFilters && <button type="button" className="clear-filters" onClick={onReset}><Close />Clear</button>}</div></div></section>;
}
