import { categoryLabel } from "../../types/job-posting";
import type { Region } from "../../services/region.service";
import { Close, Search, SlidersHorizontal } from "../site/Icons";
import { CountryCombobox } from "../site/CountryCombobox";
import { LocationFilterCombobox } from "../site/LocationFilterCombobox";

export type DateFilter = "any" | "7d" | "30d" | "range";
export type SortKey = "newest" | "oldest" | "nearest";

type Props = { query: string; category: string; country: string; province: string; location: string; dateFilter: DateFilter; from: string; to: string; sort: SortKey; categories: string[]; countries: Region[]; provinces: Region[]; locations: Region[]; provincesLoading: boolean; locationsLoading: boolean; showNearest: boolean; activeFilters: boolean; onQueryChange: (value: string) => void; onCategoryChange: (value: string) => void; onCountryChange: (value: string) => void; onProvinceChange: (value: string) => void; onLocationChange: (value: string) => void; onDateFilterChange: (value: DateFilter) => void; onFromChange: (value: string) => void; onToChange: (value: string) => void; onSortChange: (value: SortKey) => void; onReset: () => void };

export function BrowseFilters(props: Props) {
  const dateOptions: [DateFilter, string][] = [["any", "Any time"], ["7d", "Last 7 days"], ["30d", "Last 30 days"], ["range", "Date range"]];
  return <section className="browse-filters"><div className="browse-filter-wrap"><div className="browse-filter-primary"><label className="browse-search"><Search /><input value={props.query} onChange={(event) => props.onQueryChange(event.target.value)} placeholder="Job title, company or skill" /></label><select value={props.category} onChange={(event) => props.onCategoryChange(event.target.value)}><option value="all">All categories</option>{props.categories.map((item) => <option key={item} value={item}>{categoryLabel(item)}</option>)}</select><CountryCombobox value={props.country} countries={props.countries} onChange={props.onCountryChange} /><LocationFilterCombobox value={props.province} disabled={props.country === "all"} loading={props.provincesLoading} placeholder="All provinces / states" loadingLabel="Loading provinces / states…" options={props.provinces.map((item) => ({ value: item.name, label: `${item.name}, ${props.country}` }))} onChange={props.onProvinceChange} /><LocationFilterCombobox value={props.location} disabled={props.country === "all" || props.province === "all"} loading={props.locationsLoading} placeholder="All cities" loadingLabel="Loading cities…" options={props.locations.map((item) => ({ value: item.name, label: `${item.name}, ${props.province}, ${props.country}` }))} onChange={props.onLocationChange} /></div><div className="browse-filter-secondary"><span><SlidersHorizontal />Posted</span>{dateOptions.map(([value, label]) => <button key={value} type="button" className={props.dateFilter === value ? "active" : ""} onClick={() => props.onDateFilterChange(value)}>{label}</button>)}{props.dateFilter === "range" && <div className="browse-date-range"><input aria-label="From date" type="date" value={props.from} onChange={(event) => props.onFromChange(event.target.value)} /><span>to</span><input aria-label="To date" value={props.to} onChange={(event) => props.onToChange(event.target.value)} type="date" /></div>}<div className="browse-sort"><label htmlFor="browse-sort">Sort</label><select id="browse-sort" value={props.sort} onChange={(event) => props.onSortChange(event.target.value as SortKey)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option>{props.showNearest && <option value="nearest">Nearest to me</option>}</select></div>{props.activeFilters && <button type="button" className="clear-filters" onClick={props.onReset}><Close />Clear</button>}</div></div></section>;
}
