import { categoryLabel } from "../../types/job-posting";
import type { Region } from "../../services/region.service";
import { Close, Search, SlidersHorizontal } from "../site/Icons";

export type DateFilter = "any" | "7d" | "30d" | "range";
export type SortKey = "newest" | "oldest" | "nearest";

type Props = { query: string; category: string; province: string; location: string; dateFilter: DateFilter; from: string; to: string; sort: SortKey; categories: string[]; provinces: Region[]; locations: Region[]; showNearest: boolean; activeFilters: boolean; onQueryChange: (value: string) => void; onCategoryChange: (value: string) => void; onProvinceChange: (value: string) => void; onLocationChange: (value: string) => void; onDateFilterChange: (value: DateFilter) => void; onFromChange: (value: string) => void; onToChange: (value: string) => void; onSortChange: (value: SortKey) => void; onReset: () => void };

export function BrowseFilters(props: Props) {
  const dateOptions: [DateFilter, string][] = [["any", "Any time"], ["7d", "Last 7 days"], ["30d", "Last 30 days"], ["range", "Date range"]];
  return <section className="browse-filters"><div className="browse-filter-wrap"><div className="browse-filter-primary"><label className="browse-search"><Search /><input value={props.query} onChange={(event) => props.onQueryChange(event.target.value)} placeholder="Job title, company or skill" /></label><select value={props.category} onChange={(event) => props.onCategoryChange(event.target.value)}><option value="all">All categories</option>{props.categories.map((item) => <option key={item} value={item}>{categoryLabel(item)}</option>)}</select><select value={props.province} onChange={(event) => props.onProvinceChange(event.target.value)}><option value="all">Choose province</option>{props.provinces.map((item) => <option key={item.code} value={item.code}>{item.name}</option>)}</select><select value={props.location} disabled={props.province === "all"} onChange={(event) => props.onLocationChange(event.target.value)}><option value="all">Choose city/regency</option>{props.locations.map((item) => <option key={item.code} value={item.name}>{item.name}</option>)}</select></div><div className="browse-filter-secondary"><span><SlidersHorizontal />Posted</span>{dateOptions.map(([value, label]) => <button key={value} type="button" className={props.dateFilter === value ? "active" : ""} onClick={() => props.onDateFilterChange(value)}>{label}</button>)}{props.dateFilter === "range" && <div className="browse-date-range"><input aria-label="From date" type="date" value={props.from} onChange={(event) => props.onFromChange(event.target.value)} /><span>to</span><input aria-label="To date" type="date" value={props.to} onChange={(event) => props.onToChange(event.target.value)} /></div>}<div className="browse-sort"><label htmlFor="browse-sort">Sort</label><select id="browse-sort" value={props.sort} onChange={(event) => props.onSortChange(event.target.value as SortKey)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option>{props.showNearest && <option value="nearest">Nearest to me</option>}</select></div>{props.activeFilters && <button type="button" className="clear-filters" onClick={props.onReset}><Close />Clear</button>}</div></div></section>;
}
